version: "3.7"

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - SECRET_KEY=@lgmubqzn^9@u#gr15_ux4w-l8w9*8@wrv_!@hcgq#(qx1m$$2_
      - DEBUG=True
      - EMAIL_USE_SSL=True
      - EMAIL_HOST=mail.privateemail.com
      - EMAIL_HOST_USER=no-reply@mercurywapps.com
      - EMAIL_HOST_PASSWORD=Mercurio!3385
      - EMAIL_PORT=465

  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgres_data:
